language: emacs-lisp
before_install:
  # PPA for stable Emacs packages
  - sudo add-apt-repository -y ppa:cassou/emacs
  # PPA for Emacs nightlies
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # Update and install the Emacs for our environment
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10 https://raw.github.com/cask/cask/master/go | python
  - git clone git://orgmode.org/org-mode.git && cd org-mode && git checkout ${ORG} && make autoloads && cd ..
env:
  # I want to use Cask to gather dependencies
  # Cask does not support Emacs 23.
  # Therefore I don't support emacs-23
  # - EMACS=emacs23

  # test the minimum supported requirements
  # 8.2.6 fails with (error "`recenter'ing a window that does not display current-buffer.")
  - EMACS=emacs24 ORG=release_8.2.7

  # test latest released emacs and org-mode
  - EMACS=emacs24 ORG=release_8.2.10

  # test newest emacs with minimum supported org-modee
  - EMACS=emacs-snapshot ORG=release_8.2.7

  # test newest emacs with latest released org-mode
  - EMACS=emacs-snapshot ORG=release_8.2.10
script:
  - make cask
  - make test